### ISSUE TITLE
markdown reader : Dynamic Resource Pricing System Documentation

### ISSUE THREAD

**Issue by swan-alexchen** [swan-alexchen/temporary_docs#2]
# Dynamic Resource Pricing System Documentation

## Table of Contents
1. System Overview
2. Key Components
3. Workflows
4. Technical Diagrams
5. Use Cases
6. Important Considerations

## 1. System Overview
The dynamic resource pricing system implements a dual-snapshot pricing mechanism that ensures fair pricing and payment validation for resource allocation. The system maintains two pricing snapshots at any given time, updating every 10 minutes to reflect current market conditions.

## 2. Key Components
- **Pricing Service**: Creates and manages pricing snapshots
- **Smart Contract**: Stores and serves pricing information
- **Swan Backend**: Handles task creation and payment validation
- **SDK**: Client-side interface for users
- **Payment System**: Handles transaction processing

### 3.1 Pricing Update Workflow
1. Pricing Service generates new snapshot every 10 minutes
2. New snapshot is uploaded to Smart Contract
3. Smart Contract maintains:
   - Current snapshot
   - Previous snapshot (for validation)

### 3.2 Task Creation and Payment Workflow
1. User initiates task creation via SDK
2. SDK fetches current pricing from Smart Contract
3. User reviews pricing and time window (10-20 minutes)
4. User submits payment
5. Backend validates payment against accepted snapshots
6. Task creation proceeds if validation successful

### 4.1 System Component Interaction
```mermaid
graph TB
    PS[Pricing Service] -->|Updates every 10min| SC[Smart Contract]
    SC -->|Stores| CS[Current Snapshot]
    SC -->|Stores| PS2[Previous Snapshot]
    SDK -->|Reads Pricing| SC
    User -->|Interacts| SDK
    SDK -->|Submits Payment| Backend
    Backend -->|Validates| SC
    Backend -->|Creates| Task
```

### 4.2 Pricing Update Flow
```mermaid
sequenceDiagram
    participant PS as Pricing Service
    participant SC as Smart Contract
    participant SDK as SDK
    participant BE as Backend
    
    PS->>SC: Generate new snapshot
    SC->>SC: Update current snapshot
    SC->>SC: Previous snapshot = Old current snapshot
    SDK->>SC: Request pricing
    SC->>SDK: Return current snapshot
    SDK->>BE: Submit payment with snapshot ID
    BE->>SC: Validate snapshot ID
    SC->>BE: Validation result
```

### 4.3 Use Cases
```mermaid
graph TB
    subgraph "Use Cases"
    A[Task Creation] -->|Uses| B[Current Snapshot]
    C[Payment Validation] -->|Accepts| B
    C -->|Accepts| D[Previous Snapshot]
    E[Refund Process] -->|Triggers if| F[Invalid/Outdated Snapshot]
    end
```

### 5.1 Normal Task Creation
- **Scenario**: User creates task within valid timeframe
- **Flow**:
  1. User receives current pricing
  2. Completes payment within 10-20 minutes
  3. Backend validates against accepted snapshots
  4. Task created successfully

### 5.2 Expired Payment Window
- **Scenario**: User delays payment beyond valid timeframe
- **Flow**:
  1. User receives pricing snapshot
  2. Delays payment > 20 minutes
  3. Snapshot becomes invalid
  4. User must restart process with current pricing

### 5.3 Refund Scenario
- **Scenario**: Payment made with outdated snapshot
- **Flow**:
  1. Payment submitted with old snapshot ID
  2. Validation fails
  3. User eligible for refund
  4. Must restart with current pricing

### 6.1 Timing Constraints
- Snapshot updates: Every 10 minutes
- Payment window: 10-20 minutes
- Validation window: Two most recent snapshots

### 6.2 Best Practices
1. **For Developers**:
   - Always fetch fresh pricing before creating payment orders
   - Implement timeout handling for pricing display
   - Include clear expiration timestamps in UI

2. **For Users**:
   - Complete payment promptly after price check
   - Note the expiration time shown in UI
   - Request new pricing if window expires

### 6.3 Error Handling
1. **Invalid Snapshot ID**:
   - System should automatically reject
   - Provide clear error message
   - Guide user to retry with current pricing

2. **Expired Payment Window**:
   - Implement automatic expiration
   - Clear UI feedback
   - Simple path to restart process

## 7. Implementation Checklist

- [ ] Smart Contract Updates
  - [ ] Dual snapshot storage
  - [ ] Snapshot rotation logic
  - [ ] Validation methods

- [ ] Backend Services
  - [ ] Pricing snapshot generation
  - [ ] Payment validation logic
  - [ ] Refund processing

- [ ] SDK Implementation
  - [ ] Price fetching
  - [ ] Payment window display
  - [ ] Error handling

- [ ] Testing
  - [ ] Snapshot rotation
  - [ ] Payment validation
  - [ ] Edge cases

**Comment by swan-alexchen** [comment]
the background for AI:

dynamic resource prcing system implementation plan

# overview
## pricing information update and use cases
1. make one full resource pricing snapshot in every 10 minutes with a snapshot id
2. put the latest full resource pricing snapshot to the smart contract.
3. the smart contract always keep 2 different copies of the pricing snapshot, the current one and the previous one.
4. there are 2 use cases from these 2 pricing snapshots in the smart contract
    4.1. when the swan backend is creating a task payment order, the resource price should be coming from the current snapshot
    4.2. when the swan backend is validating the task payment, the snapshot id in the payment order should be one of the current snapshot and the previous snapshot, otherwise the snapshot id of the payment order is invalid or outdated, users can apply for refund for a paid task payment 

Note:
Since there are 2 pricing snapshots in the smart contract, and the resource price will always fetch from the current snapshot, so the expiry time of a task payment order will be alway within 10 - 20mins later

# task creation workflow
1. SDK reads the current resource pricing from the smart contract, show them to the users ( money amount, pricing snapshot id, time left to finish the payment and to submit to our backend for validation: 10 - 20mins in our 2 snapshots design)
2. after user paid, the SDK calls for validation with the payment reciept, once finished validation, the workflow is pretty the same with the existing one on fixed resource pricing.
